@Api_HostAddress = https://localhost:5078

### liveliness check:
GET {{Api_HostAddress}}/health/live
Accept: application/json

### readiness check:
GET {{Api_HostAddress}}/api/health/ready
Accept: application/json
X-API-Key: 123
