@Api_HostAddress = https://localhost:5078

### liveliness check:
# @no-reject-unauthorized
GET {{Api_HostAddress}}/health/live
Accept: application/json

### readiness check:
# @no-reject-unauthorized
GET {{Api_HostAddress}}/api/health/ready
Accept: application/json
X-API-Key: {{ApiKeyDev}}

### Open API:
# @no-reject-unauthorized
GET {{Api_HostAddress}}/openapi/v1.json
Accept: application/json
X-API-Key: {{ApiKeyDev}}

### Scalar:
# @no-reject-unauthorized
{{Api_HostAddress}}/scalar/v1
